Hw02 unpack string
Dmitry-Tsarkov/hw-test pull request #2
Opened 2024-04-10 21:18 UTC by Dmitry-Tsarkov

К сожалению, срок сдачи дз увидел только вчера (09.04) и не успел доделать задание до конца. Делаю пул реквест чтобы показать прогресс на данный момент. Собираюсь доделать.

2024-04-15 15:45 UTC, Dmitry-Tsarkov commented
Дз доделал

2024-04-16 04:20 UTC, agneum requested changes
Спасибо за вариант решения, хорошая работа
Будет здорово, если получится добавить новые юнит-тесты
Итого: 6 баллов из 10. Возвращаю задачу на доработку

2024-04-16 04:20 UTC, agneum commented on hw02_unpack_string/unpack.go
> +				prev = 0
Надёжнее будет использовать флаг наличия/отсутствия предыдущего символа, потому что 0 - кажется, валидное значение

2024-04-22 09:50 UTC, Dmitry-Tsarkov commented
Я правильно понял, что под "добавлением новых юнит-тестов" понимается расширение структуры дополнительными кейсами?

2024-04-23 00:49 UTC, agneum commented
> Я правильно понял, что под "добавлением новых юнит-тестов" понимается расширение структуры дополнительными кейсами?

Да, новые кейсы - это одно из возможных решений. Можно так же добавить собственные тесты

2024-04-23 00:49 UTC, agneum approved these changes
Спасибо за тесты. Принято

2024-06-20 14:49 UTC, merged